#!/usr/bin/env bash
# bash

sudo cp /etc/hosts /etc/hosts.bak

sudo sed -i '/127.0.0.2[[:space:]]\+localhost/d' /etc/hosts
sudo sed -i '/8.8.8.8[[:space:]]\+facebook.com/d' /etc/hosts

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

cat /etc/hosts
